In [135]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import warnings
warnings.filterwarnings('ignore')
import re
from bs4 import BeautifulSoup
import time

In [2]:
Hotel_Name=[]
Location=[]
ratings=[]
final_prices=[]
Orginal_prices=[]
Discounts=[]
Taxes=[]
Wizard_members=[]
amenities=[]
Company_serviceable=[]

In [3]:
Hyd_Hotel_Name=[]
Hyd_Location=[]
Hyd_ratings=[]
Hyd_final_price=[]
Hyd_Orginal_price=[]
Hyd_Discount=[]
Hyd_Taxes=[]
Hyd_Wizard_member=[]
Hyd_amenities=[]
Hyd_Company_serviced=[]

In [4]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Referer": "https://www.oyorooms.com/",
    "Upgrade-Insecure-Requests": "1",
}

In [5]:
total_time = time.time()
for page_num in range(1,28):
    start_time = time.time()
    url=f'https://www.oyorooms.com/hotels-in-hyderabad/?gad_campaignid=1701551904&gad_source=1&gbraid=0AAAAADj-OgRSvN41kmX5yqMh3tE0IdeB7&gclid=Cj0KCQiAgvPKBhCxARIsAOlK_Epy3H9btpY64x0Xaok9Ck1oQaFvjzQGjECXYm7uqIOQN40iqb3NvesaAqjFEALw_wcB&page={page_num}&utm_adgroup=143959616297&utm_campaign=India_SEM_Brand_generic&utm_campaignid=1701551904&utm_content=751298002022&utm_device=c&utm_keyword=oyo&utm_medium=cpc&utm_source=google'
    page=requests.get(url,headers=headers)
    soup = BeautifulSoup(page.text, "html.parser")
    for x in soup.find_all('div', class_='oyo-row oyo-row--no-spacing hotelCardListing'):

        Hotelname = x.find('h3', class_="listingHotelDescription__hotelName d-textEllipsis")
        Location = x.find('span', class_="u-line--clamp-2")
        rating = x.find('div', class_='hotelRating')
        finalprice = x.find('span', class_='listingPrice__finalPrice listingPrice__finalPrice--black')
        Orginal_price = x.find('span', class_='listingPrice__slashedPrice d-body-lg')
        discount = x.find('span', class_='listingPrice__percentage')
        tax = x.find('div', class_='listingPrice__perRoomNight')
        wizard_member = x.find('div', class_='c-1vsluwb')
        amenities = x.find('div', class_='amenityWrapper')
        company_serviced = "Yes" if x.find(
            "img", src=lambda s: s and "company_serviced" in s
        ) else "No"
    

        Hyd_Hotel_Name.append(Hotelname.text.strip() if Hotelname else np.nan)
        Hyd_Location.append(Location.text.strip() if Location else np.nan)
        Hyd_ratings.append(rating.text.strip() if rating else np.nan)
        Hyd_final_price.append(finalprice.text.strip() if finalprice else np.nan)
        Hyd_Orginal_price.append(Orginal_price.text.strip() if Orginal_price else np.nan)
        Hyd_Discount.append(discount.text.strip() if discount else np.nan)
        Hyd_Taxes.append(tax.text.strip() if tax else np.nan)
        Hyd_Wizard_member.append(wizard_member.text.strip() if wizard_member else np.nan)
        Hyd_amenities.append(amenities.text.strip() if amenities else np.nan)
        Hyd_Company_serviced.append(company_serviced)

        
    print(f'Page {page_num} completed in {time.time()-start_time:.2f} seconds')
print("Total Time Completed in seconds", str(time.time()-total_time))

Page 1 completed in 5.43 seconds
Page 2 completed in 4.21 seconds
Page 3 completed in 4.00 seconds
Page 4 completed in 3.95 seconds
Page 5 completed in 4.09 seconds
Page 6 completed in 4.19 seconds
Page 7 completed in 4.11 seconds
Page 8 completed in 4.11 seconds
Page 9 completed in 4.04 seconds
Page 10 completed in 4.99 seconds
Page 11 completed in 4.57 seconds
Page 12 completed in 6.09 seconds
Page 13 completed in 4.83 seconds
Page 14 completed in 3.95 seconds
Page 15 completed in 4.00 seconds
Page 16 completed in 4.38 seconds
Page 17 completed in 4.89 seconds
Page 18 completed in 4.24 seconds
Page 19 completed in 4.47 seconds
Page 20 completed in 4.32 seconds
Page 21 completed in 3.90 seconds
Page 22 completed in 4.09 seconds
Page 23 completed in 3.93 seconds
Page 24 completed in 4.19 seconds
Page 25 completed in 4.06 seconds
Page 26 completed in 4.15 seconds
Page 27 completed in 3.45 seconds
Total Time Completed in seconds 116.64162683486938

In [62]:
print(len(Hyd_Hotel_Name))
print(len(Hyd_Location))
print(len(Hyd_ratings))
print(len(Hyd_final_price))
print(len(Hyd_Orginal_price))
print(len(Hyd_Discount))
print(len(Hyd_Taxes))
print(len(Hyd_Wizard_member))
print(len(Hyd_amenities))
print(len(Hyd_Company_serviced))

470
470
470
470
470
470
470
470
470
470

In [63]:
for i,j in zip(Hyd_Hotel_Name[:10],Hyd_Location):
    print(i,j,sep='\n')

Townhouse Narayanaguda Metro Station Formerly Hotel Anshu Grand
Near Old MLA Quarters, Himayathnagar, Hyderabad
Townhouse Kothapet Formerly Surabhi Elite
Kothapet, Hyderabad
Townhouse Oak Madhapur Nera Regency
Madhapur, Hyderabad
Hotel O by OYO Saraswathi Residency Near SR Nagar Metro Station
Near Nalanda School, S.R. Nagar, Hyderabad
Super Townhouse OAK Hotel Belsons Taj Mahal
Near Swapnalok Complex, Patny Centre, Hyderabad
Super Collection O Begumpet Formerly Alpine Glow Sunrise
Near RBI Quarters, Begumpet, Hyderabad
Collection O Hi-Tec City Center Metro Station Hyderabad Formerly Hotel Blue Dawn
VIP Hills, Madhapur, Hyderabad
Super Collection O Lotus Grand
Secunderabad, Hyderabad
Hotel O Ssr Luxury Rooms
Beside Vijaya Bank, Hyderabad
Hotel O Al shareef Residency
Near Mir Chowk Police Station, Patthargatti, Hyderabad

# Banglore

In [20]:
Bng_Hotel_Name = []
Bng_Location = []
Bng_ratings = []
Bng_final_price = []
Bng_Orginal_price = []
Bng_Discount = []
Bng_Taxes = []
Bng_Wizard_member = []
Bng_amenities = []
Bng_Company_serviced = []

In [21]:
total_time = time.time()
for page_num in range(1,19):
    start_time = time.time()
    url=f'https://www.oyorooms.com/hotels-in-bangalore/?gad_campaignid=1701551904&gad_source=1&gbraid=0AAAAADj-OgRSvN41kmX5yqMh3tE0IdeB7&gclid=Cj0KCQiAgvPKBhCxARIsAOlK_Epy3H9btpY64x0Xaok9Ck1oQaFvjzQGjECXYm7uqIOQN40iqb3NvesaAqjFEALw_wcB&page={page_num}&utm_adgroup=143959616297&utm_campaign=India_SEM_Brand_generic&utm_campaignid=1701551904&utm_content=751298002022&utm_device=c&utm_keyword=oyo&utm_medium=cpc&utm_source=google'

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.text, "html.parser")

    for x in soup.find_all('div', class_='oyo-row oyo-row--no-spacing hotelCardListing'):

        Hotelname = x.find('h3', class_="listingHotelDescription__hotelName d-textEllipsis")
        Location = x.find('span', class_="u-line--clamp-2")
        rating = x.find('div', class_='hotelRating')
        finalprice = x.find('span', class_='listingPrice__finalPrice listingPrice__finalPrice--black')
        Orginal_price = x.find('span', class_='listingPrice__slashedPrice d-body-lg')
        discount = x.find('span', class_='listingPrice__percentage')
        tax = x.find('div', class_='listingPrice__perRoomNight')
        wizard_member = x.find('div', class_='c-1vsluwb')
        amenities = x.find('div', class_='amenityWrapper')

        company_serviced = "Yes" if x.find(
            "img", src=lambda s: s and "company_serviced" in s
        ) else "No"

        # ✅ APPEND TO BANGALORE LISTS
        Bng_Hotel_Name.append(Hotelname.text.strip() if Hotelname else np.nan)
        Bng_Location.append(Location.text.strip() if Location else np.nan)
        Bng_ratings.append(rating.text.strip() if rating else np.nan)
        Bng_final_price.append(finalprice.text.strip() if finalprice else np.nan)
        Bng_Orginal_price.append(Orginal_price.text.strip() if Orginal_price else np.nan)
        Bng_Discount.append(discount.text.strip() if discount else np.nan)
        Bng_Taxes.append(tax.text.strip() if tax else np.nan)
        Bng_Wizard_member.append(wizard_member.text.strip() if wizard_member else np.nan)
        Bng_amenities.append(amenities.text.strip() if amenities else np.nan)
        Bng_Company_serviced.append(company_serviced)

    print(f'Page {page_num} completed in {time.time()-start_time:.2f} seconds')

print("Total Time Completed in seconds", str(time.time()-total_time))

Page 1 completed in 4.42 seconds
Page 2 completed in 3.87 seconds
Page 3 completed in 4.34 seconds
Page 4 completed in 3.95 seconds
Page 5 completed in 5.18 seconds
Page 6 completed in 4.64 seconds
Page 7 completed in 3.88 seconds
Page 8 completed in 3.91 seconds
Page 9 completed in 4.65 seconds
Page 10 completed in 4.60 seconds
Page 11 completed in 3.51 seconds
Page 12 completed in 4.53 seconds
Page 13 completed in 3.71 seconds
Page 14 completed in 3.80 seconds
Page 15 completed in 4.00 seconds
Page 16 completed in 3.87 seconds
Page 17 completed in 4.72 seconds
Page 18 completed in 7.37 seconds
Total Time Completed in seconds 78.96502327919006

In [48]:
print(len(Bng_Hotel_Name))
print(len(Bng_Location))
print(len(Bng_ratings))
print(len(Bng_final_price))
print(len(Bng_Orginal_price))
print(len(Bng_Discount))
print(len(Bng_Taxes))
print(len(Bng_Wizard_member))
print(len(Bng_amenities))
print(len(Bng_Company_serviced))

290
290
290
290
290
290
290
290
290
290

In [49]:
for i,j in zip(Bng_Hotel_Name[:10],Bng_Location):
    print(i,j,sep='\n')

Super Collection O REVA University Rukmini Knowledge Park
Jala Hobli, Bangalore
Hotel O Srigandhakavalu Formerly Chamundeshwari Lodging
Srigandhakavalu, Bangalore
Super Townhouse BTM Layout Near Madiwala Lake Formerly Q Rooms
Near BTM Water Tank, Mico Layout, Bangalore
Super Townhouse Oak DLF Newtown Formerly South Square
Yelenahalli, Bangalore
Super Hotel O Hennagara Rd Bommasandara
Bommasandra, Bangalore
Super Hotel O Jodi Sri Muneshwara Swamy Temple
Hegganahalli Village, Bangalore
Collection O Uttarahalli
Uttarahalli, Bangalore
Townhouse HAL Aerospace Museum Formerly Krishna Boutique
Marathahalli, Bangalore
Super Townhouse Madiwala Lake Park
PID No 65-50-90, Bangalore
Super Townhouse Ulsoor Near Halasuru Metro Station
Halasuru, Bangalore

# Delhi

In [23]:
Del_Hotel_Name = []
Del_Location = []
Del_ratings = []
Del_final_price = []
Del_Orginal_price = []
Del_Discount = []
Del_Taxes = []
Del_Wizard_member = []
Del_amenities = []
Del_Company_serviced = []

In [25]:
total_time = time.time()
for page_num in range(1,21):
    start_time = time.time()
    url=f'https://www.oyorooms.com/hotels-in-delhi/?gad_campaignid=1701551904&gad_source=1&gbraid=0AAAAADj-OgRSvN41kmX5yqMh3tE0IdeB7&gclid=Cj0KCQiAgvPKBhCxARIsAOlK_Epy3H9btpY64x0Xaok9Ck1oQaFvjzQGjECXYm7uqIOQN40iqb3NvesaAqjFEALw_wcB&page={page_num}&utm_adgroup=143959616297&utm_campaign=India_SEM_Brand_generic&utm_campaignid=1701551904&utm_content=751298002022&utm_device=c&utm_keyword=oyo&utm_medium=cpc&utm_source=google'

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.text, "html.parser")

    for x in soup.find_all('div', class_='oyo-row oyo-row--no-spacing hotelCardListing'):

        Hotelname = x.find('h3', class_="listingHotelDescription__hotelName d-textEllipsis")
        Location = x.find('span', class_="u-line--clamp-2")
        rating = x.find('div', class_='hotelRating')
        finalprice = x.find('span', class_='listingPrice__finalPrice listingPrice__finalPrice--black')
        Orginal_price = x.find('span', class_='listingPrice__slashedPrice d-body-lg')
        discount = x.find('span', class_='listingPrice__percentage')
        tax = x.find('div', class_='listingPrice__perRoomNight')
        wizard_member = x.find('div', class_='c-1vsluwb')
        amenities = x.find('div', class_='amenityWrapper')

        company_serviced = "Yes" if x.find(
            "img", src=lambda s: s and "company_serviced" in s
        ) else "No"

        Del_Hotel_Name.append(Hotelname.text.strip() if Hotelname else np.nan)
        Del_Location.append(Location.text.strip() if Location else np.nan)
        Del_ratings.append(rating.text.strip() if rating else np.nan)
        Del_final_price.append(finalprice.text.strip() if finalprice else np.nan)
        Del_Orginal_price.append(Orginal_price.text.strip() if Orginal_price else np.nan)
        Del_Discount.append(discount.text.strip() if discount else np.nan)
        Del_Taxes.append(tax.text.strip() if tax else np.nan)
        Del_Wizard_member.append(wizard_member.text.strip() if wizard_member else np.nan)
        Del_amenities.append(amenities.text.strip() if amenities else np.nan)
        Del_Company_serviced.append(company_serviced)


    print(f'Page {page_num} completed in {time.time()-start_time:.2f} seconds')

print("Total Time Completed in seconds", str(time.time()-total_time))

Page 1 completed in 4.19 seconds
Page 2 completed in 4.63 seconds
Page 3 completed in 4.22 seconds
Page 4 completed in 4.29 seconds
Page 5 completed in 4.47 seconds
Page 6 completed in 4.18 seconds
Page 7 completed in 4.16 seconds
Page 8 completed in 5.15 seconds
Page 9 completed in 4.33 seconds
Page 10 completed in 3.98 seconds
Page 11 completed in 4.39 seconds
Page 12 completed in 4.22 seconds
Page 13 completed in 4.02 seconds
Page 14 completed in 5.23 seconds
Page 15 completed in 4.23 seconds
Page 16 completed in 4.33 seconds
Page 17 completed in 4.34 seconds
Page 18 completed in 4.50 seconds
Page 19 completed in 4.95 seconds
Page 20 completed in 4.94 seconds
Total Time Completed in seconds 88.75043988227844

In [50]:
print(len(Del_Hotel_Name))
print(len(Del_Location))
print(len(Del_ratings))
print(len(Del_final_price))
print(len(Del_Orginal_price))
print(len(Del_Discount))
print(len(Del_Taxes))
print(len(Del_Wizard_member))
print(len(Del_amenities))
print(len(Del_Company_serviced))

329
329
329
329
329
329
329
329
329
329

In [51]:
for i,j in zip(Del_Hotel_Name[:10],Del_Location):
    print(i,j,sep='\n')

Hotel O J P Inn Near Patel Nagar Metro Station
Near Patel Nagar Metro, Block 1, Delhi
Townhouse Hotel Lotus Palace
Near CR Park Market 1, Govindpuri Extension, Delhi
Super Collection O Lotus Bed & Breakfast
L-2,  1st Floor, B Block, Near Kabootar Chowk, C R Park Near CR Park Market 1, Pamposh Enclave, Delhi
Hotel O Kalkaji Residency Bnb Near Lotus Temple
Near Govind Puri Metro Station, Delhi
Super Collection O Hamilton Hotel
Panchsheel Park South, Delhi
Townhouse Karol Bagh Formerly Hotel Unistar
Near Faiz Road, Karol Bagh, Delhi
Super Hotel Delhi Darbar
Near Karol Bagh, WEA, Delhi
Palette Hotel Cotts Villa Vasant Kunj New Delhi
Bhawani Kunj, Delhi
Townhouse Arakashan Road Paharganj Formerly Mohan international
Near New Delhi Railway Station, Delhi
Hotel O by OYO HERITAGE RESIDENCY
Near Deshbandhu College Bus Stand, Kalkaji, Delhi

# Mumbai

In [28]:
Mum_Hotel_Name = []
Mum_Location = []
Mum_ratings = []
Mum_final_price = []
Mum_Orginal_price = []
Mum_Discount = []
Mum_Taxes = []
Mum_Wizard_member = []
Mum_amenities = []
Mum_Company_serviced = []

In [29]:
total_time = time.time()
for page_num in range(1,10):
    start_time = time.time()
    url=f'https://www.oyorooms.com/hotels-in-mumbai/?gad_campaignid=1701551904&gad_source=1&gbraid=0AAAAADj-OgRSvN41kmX5yqMh3tE0IdeB7&gclid=Cj0KCQiAgvPKBhCxARIsAOlK_Epy3H9btpY64x0Xaok9Ck1oQaFvjzQGjECXYm7uqIOQN40iqb3NvesaAqjFEALw_wcB&page={page_num}&utm_adgroup=143959616297&utm_campaign=India_SEM_Brand_generic&utm_campaignid=1701551904&utm_content=751298002022&utm_device=c&utm_keyword=oyo&utm_medium=cpc&utm_source=google'

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.text, "html.parser")

    for x in soup.find_all('div', class_='oyo-row oyo-row--no-spacing hotelCardListing'):

        Hotelname = x.find('h3', class_="listingHotelDescription__hotelName d-textEllipsis")
        Location = x.find('span', class_="u-line--clamp-2")
        rating = x.find('div', class_='hotelRating')
        finalprice = x.find('span', class_='listingPrice__finalPrice listingPrice__finalPrice--black')
        Orginal_price = x.find('span', class_='listingPrice__slashedPrice d-body-lg')
        discount = x.find('span', class_='listingPrice__percentage')
        tax = x.find('div', class_='listingPrice__perRoomNight')
        wizard_member = x.find('div', class_='c-1vsluwb')
        amenities = x.find('div', class_='amenityWrapper')

        company_serviced = "Yes" if x.find(
            "img", src=lambda s: s and "company_serviced" in s
        ) else "No"

        Mum_Hotel_Name.append(Hotelname.text.strip() if Hotelname else np.nan)
        Mum_Location.append(Location.text.strip() if Location else np.nan)
        Mum_ratings.append(rating.text.strip() if rating else np.nan)
        Mum_final_price.append(finalprice.text.strip() if finalprice else np.nan)
        Mum_Orginal_price.append(Orginal_price.text.strip() if Orginal_price else np.nan)
        Mum_Discount.append(discount.text.strip() if discount else np.nan)
        Mum_Taxes.append(tax.text.strip() if tax else np.nan)
        Mum_Wizard_member.append(wizard_member.text.strip() if wizard_member else np.nan)
        Mum_amenities.append(amenities.text.strip() if amenities else np.nan)
        Mum_Company_serviced.append(company_serviced)



    print(f'Page {page_num} completed in {time.time()-start_time:.2f} seconds')

print("Total Time Completed in seconds", str(time.time()-total_time))

Page 1 completed in 3.60 seconds
Page 2 completed in 3.69 seconds
Page 3 completed in 3.59 seconds
Page 4 completed in 3.40 seconds
Page 5 completed in 3.08 seconds
Page 6 completed in 4.56 seconds
Page 7 completed in 3.19 seconds
Page 8 completed in 2.98 seconds
Page 9 completed in 2.56 seconds
Total Time Completed in seconds 30.656484365463257

In [52]:
print(len(Mum_Hotel_Name))
print(len(Mum_Location))
print(len(Mum_ratings))
print(len(Mum_final_price))
print(len(Mum_Orginal_price))
print(len(Mum_Discount))
print(len(Mum_Taxes))
print(len(Mum_Wizard_member))
print(len(Mum_amenities))
print(len(Mum_Company_serviced))

141
141
141
141
141
141
141
141
141
141

In [53]:
for i,j in zip(Mum_Hotel_Name[:10],Mum_Location):
    print(i,j,sep='\n')

Super Townhouse PBG Mall Vashi
India, Mumbai
Super Collection O Kalyan East
Kalyan East, Mumbai
Super Townhouse Bombay Exhibition Centre Goregaon
Ram Mandir Road,Goregaon West, Mumbai
Super Townhouse Marol Near Mumbai Airport
Marol, Mumbai
Super Hotel O Dombivali Formerly PK Lodging
Dombiwali East, Mumbai
Super Hotel O Kharbao Bhiwandi Thane
Near Malodi Toll Phata, On S.no 40, H No 6, At Village Kharbao, Ta Bhiwandi, Dist Thane, Mumbai
Hotel O Ambedkar Chowk Ulhasnagar
Near Chopra Court, Mumbai
Super Collection O Andheri Near Western Express Highway
Andheri East, Mumbai
Super Collection O Lokhandwala Andheri West Formerly White Star
Near Jankidevi School Rd, SV Patel Nagar, Mumbai
Super Collection O Lodha Experia Mall Dombiwali Formerly RR Suites
Dombivli East, Mumbai

# Chennai

In [32]:
Che_Hotel_Name = []
Che_Location = []
Che_ratings = []
Che_final_price = []
Che_Orginal_price = []
Che_Discount = []
Che_Taxes = []
Che_Wizard_member = []
Che_amenities = []
Che_Company_serviced = []

In [33]:
total_time = time.time()
for page_num in range(1,11):
    start_time = time.time()
    url=f'https://www.oyorooms.com/hotels-in-chennai/?gad_campaignid=1701551904&gad_source=1&gbraid=0AAAAADj-OgRSvN41kmX5yqMh3tE0IdeB7&gclid=Cj0KCQiAgvPKBhCxARIsAOlK_Epy3H9btpY64x0Xaok9Ck1oQaFvjzQGjECXYm7uqIOQN40iqb3NvesaAqjFEALw_wcB&page={page_num}&utm_adgroup=143959616297&utm_campaign=India_SEM_Brand_generic&utm_campaignid=1701551904&utm_content=751298002022&utm_device=c&utm_keyword=oyo&utm_medium=cpc&utm_source=google'

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.text, "html.parser")

    for x in soup.find_all('div', class_='oyo-row oyo-row--no-spacing hotelCardListing'):

        Hotelname = x.find('h3', class_="listingHotelDescription__hotelName d-textEllipsis")
        Location = x.find('span', class_="u-line--clamp-2")
        rating = x.find('div', class_='hotelRating')
        finalprice = x.find('span', class_='listingPrice__finalPrice listingPrice__finalPrice--black')
        Orginal_price = x.find('span', class_='listingPrice__slashedPrice d-body-lg')
        discount = x.find('span', class_='listingPrice__percentage')
        tax = x.find('div', class_='listingPrice__perRoomNight')
        wizard_member = x.find('div', class_='c-1vsluwb')
        amenities = x.find('div', class_='amenityWrapper')

        company_serviced = "Yes" if x.find(
            "img", src=lambda s: s and "company_serviced" in s
        ) else "No"

        Che_Hotel_Name.append(Hotelname.text.strip() if Hotelname else np.nan)
        Che_Location.append(Location.text.strip() if Location else np.nan)
        Che_ratings.append(rating.text.strip() if rating else np.nan)
        Che_final_price.append(finalprice.text.strip() if finalprice else np.nan)
        Che_Orginal_price.append(Orginal_price.text.strip() if Orginal_price else np.nan)
        Che_Discount.append(discount.text.strip() if discount else np.nan)
        Che_Taxes.append(tax.text.strip() if tax else np.nan)
        Che_Wizard_member.append(wizard_member.text.strip() if wizard_member else np.nan)
        Che_amenities.append(amenities.text.strip() if amenities else np.nan)
        Che_Company_serviced.append(company_serviced)




    print(f'Page {page_num} completed in {time.time()-start_time:.2f} seconds')

print("Total Time Completed in seconds", str(time.time()-total_time))

Page 1 completed in 5.07 seconds
Page 2 completed in 3.51 seconds
Page 3 completed in 4.17 seconds
Page 4 completed in 4.01 seconds
Page 5 completed in 3.73 seconds
Page 6 completed in 3.25 seconds
Page 7 completed in 4.84 seconds
Page 8 completed in 2.98 seconds
Page 9 completed in 3.24 seconds
Page 10 completed in 2.68 seconds
Total Time Completed in seconds 37.46958565711975

In [54]:
print(len(Che_Hotel_Name))
print(len(Che_Location))
print(len(Che_ratings))
print(len(Che_final_price))
print(len(Che_Orginal_price))
print(len(Che_Discount))
print(len(Che_Taxes))
print(len(Che_Wizard_member))
print(len(Che_amenities))
print(len(Che_Company_serviced))

163
163
163
163
163
163
163
163
163
163

In [55]:
for i,j in zip(Che_Hotel_Name[:10],Che_Location):
    print(i,j,sep='\n')

Super Collection O Sathyabama University Sithalapakkam Formerly Srinivasa Residency
Sithalapakkam, Chennai
Hotel O Grand Residency
Kamaraj street, Parameswaran Nagar, Shollinganallur,Chennai, Near Ponniamman Kovil
Super Hotel O Oragadam Industrial Estates Chennai Formerly SSM Rooms
Near Perumalpattu - Kottamedu Road, Chennai
Super Hotel O Tiruvallur Bus Terminal Formerly SK Vinoth Mahal
Tiruvallur, Chennai
Super Hotel O Janappanchatram
Janappachathiram Koot Road, Chennai
Super Collection O Chidambaram Stadium Formerly Hotel Admire Suit
Triplicane, Chennai
Super Hotel O Triplicane Formerly Park Royal
Triplicane, Chennai
Super Hotel O Nemeli Road Sriram Nagar
Sriperumbathur, Chennai
Collection O Nibav Beach View
Near Nibav beach ECR Soolerikadu, Chennai
Super Townhouse Medavakkam Near Jayachandran
Near Vedanta School, Medavakkam,Chennai

# Pune

In [38]:
Pun_Hotel_Name = []
Pun_Location = []
Pun_ratings = []
Pun_final_price = []
Pun_Orginal_price = []
Pun_Discount = []
Pun_Taxes = []
Pun_Wizard_member = []
Pun_amenities = []
Pun_Company_serviced = []

In [39]:
total_time = time.time()
for page_num in range(1,11):
    start_time = time.time()
    url=f'https://www.oyorooms.com/hotels-in-pune/?gad_campaignid=1701551904&gad_source=1&gbraid=0AAAAADj-OgRSvN41kmX5yqMh3tE0IdeB7&gclid=Cj0KCQiAgvPKBhCxARIsAOlK_Epy3H9btpY64x0Xaok9Ck1oQaFvjzQGjECXYm7uqIOQN40iqb3NvesaAqjFEALw_wcB&page={page_num}&utm_adgroup=143959616297&utm_campaign=India_SEM_Brand_generic&utm_campaignid=1701551904&utm_content=751298002022&utm_device=c&utm_keyword=oyo&utm_medium=cpc&utm_source=google'

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.text, "html.parser")

    for x in soup.find_all('div', class_='oyo-row oyo-row--no-spacing hotelCardListing'):

        Hotelname = x.find('h3', class_="listingHotelDescription__hotelName d-textEllipsis")
        Location = x.find('span', class_="u-line--clamp-2")
        rating = x.find('div', class_='hotelRating')
        finalprice = x.find('span', class_='listingPrice__finalPrice listingPrice__finalPrice--black')
        Orginal_price = x.find('span', class_='listingPrice__slashedPrice d-body-lg')
        discount = x.find('span', class_='listingPrice__percentage')
        tax = x.find('div', class_='listingPrice__perRoomNight')
        wizard_member = x.find('div', class_='c-1vsluwb')
        amenities = x.find('div', class_='amenityWrapper')

        company_serviced = "Yes" if x.find(
            "img", src=lambda s: s and "company_serviced" in s
        ) else "No"

        Pun_Hotel_Name.append(Hotelname.text.strip() if Hotelname else np.nan)
        Pun_Location.append(Location.text.strip() if Location else np.nan)
        Pun_ratings.append(rating.text.strip() if rating else np.nan)
        Pun_final_price.append(finalprice.text.strip() if finalprice else np.nan)
        Pun_Orginal_price.append(Orginal_price.text.strip() if Orginal_price else np.nan)
        Pun_Discount.append(discount.text.strip() if discount else np.nan)
        Pun_Taxes.append(tax.text.strip() if tax else np.nan)
        Pun_Wizard_member.append(wizard_member.text.strip() if wizard_member else np.nan)
        Pun_amenities.append(amenities.text.strip() if amenities else np.nan)
        Pun_Company_serviced.append(company_serviced)





    print(f'Page {page_num} completed in {time.time()-start_time:.2f} seconds')

print("Total Time Completed in seconds", str(time.time()-total_time))

Page 1 completed in 3.84 seconds
Page 2 completed in 4.06 seconds
Page 3 completed in 3.82 seconds
Page 4 completed in 5.06 seconds
Page 5 completed in 3.31 seconds
Page 6 completed in 3.72 seconds
Page 7 completed in 3.78 seconds
Page 8 completed in 3.44 seconds
Page 9 completed in 3.19 seconds
Page 10 completed in 2.93 seconds
Total Time Completed in seconds 37.135910987854004

In [56]:
print(len(Pun_Hotel_Name))
print(len(Pun_Location))
print(len(Pun_ratings))
print(len(Pun_final_price))
print(len(Pun_Orginal_price))
print(len(Pun_Discount))
print(len(Pun_Taxes))
print(len(Pun_Wizard_member))
print(len(Pun_amenities))
print(len(Pun_Company_serviced))

150
150
150
150
150
150
150
150
150
150

In [57]:
for i,j in zip(Pun_Hotel_Name[:10],Pun_Location):
    print(i,j,sep='\n')

Collection O Laxmi Chowk Hinjewadi
Hinjewadi Phase 1, Pune
Super Hotel O Laxmi Chowk Hinjewadi
Hinjewadi, Pune
Super Townhouse Lohegaon Near Pune Airport Formerly Landmark Regency
Lohegaon, Pune
Super Collection O Hinjewadi Phase 1 Formerly Mars Venture
Hinjewadi, Pune
Super Hotel O Manjari Road
Hadapsar, Pune
Super Townhouse Ambegaon Road Katraj Formerly White Castle
Katraj, Pune
Super Hotel O Dhanori Near Pune Airport
Dhanori-Lohegaon, Pune
Super Townhouse Hinjewadi Corporate Stays
Hinjewadi Phase 1, Pune
Super Townhouse Amanora Park Town Formerly Samrat Inn
Amanora-Hadapsar, Pune
Super Hotel O Pioneer
Dange Chowk, Pune

# Kolkata

In [42]:
Kol_Hotel_Name = []
Kol_Location = []
Kol_ratings = []
Kol_final_price = []
Kol_Orginal_price = []
Kol_Discount = []
Kol_Taxes = []
Kol_Wizard_member = []
Kol_amenities = []
Kol_Company_serviced = []

In [43]:
total_time = time.time()
for page_num in range(1,17):
    start_time = time.time()
    url=f'https://www.oyorooms.com/hotels-in-kolkata/?gad_campaignid=1701551904&gad_source=1&gbraid=0AAAAADj-OgRSvN41kmX5yqMh3tE0IdeB7&gclid=Cj0KCQiAgvPKBhCxARIsAOlK_Epy3H9btpY64x0Xaok9Ck1oQaFvjzQGjECXYm7uqIOQN40iqb3NvesaAqjFEALw_wcB&page={page_num}&utm_adgroup=143959616297&utm_campaign=India_SEM_Brand_generic&utm_campaignid=1701551904&utm_content=751298002022&utm_device=c&utm_keyword=oyo&utm_medium=cpc&utm_source=google'

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.text, "html.parser")

    for x in soup.find_all('div', class_='oyo-row oyo-row--no-spacing hotelCardListing'):

        Hotelname = x.find('h3', class_="listingHotelDescription__hotelName d-textEllipsis")
        Location = x.find('span', class_="u-line--clamp-2")
        rating = x.find('div', class_='hotelRating')
        finalprice = x.find('span', class_='listingPrice__finalPrice listingPrice__finalPrice--black')
        Orginal_price = x.find('span', class_='listingPrice__slashedPrice d-body-lg')
        discount = x.find('span', class_='listingPrice__percentage')
        tax = x.find('div', class_='listingPrice__perRoomNight')
        wizard_member = x.find('div', class_='c-1vsluwb')
        amenities = x.find('div', class_='amenityWrapper')

        company_serviced = "Yes" if x.find(
            "img", src=lambda s: s and "company_serviced" in s
        ) else "No"

        Kol_Hotel_Name.append(Hotelname.text.strip() if Hotelname else np.nan)
        Kol_Location.append(Location.text.strip() if Location else np.nan)
        Kol_ratings.append(rating.text.strip() if rating else np.nan)
        Kol_final_price.append(finalprice.text.strip() if finalprice else np.nan)
        Kol_Orginal_price.append(Orginal_price.text.strip() if Orginal_price else np.nan)
        Kol_Discount.append(discount.text.strip() if discount else np.nan)
        Kol_Taxes.append(tax.text.strip() if tax else np.nan)
        Kol_Wizard_member.append(wizard_member.text.strip() if wizard_member else np.nan)
        Kol_amenities.append(amenities.text.strip() if amenities else np.nan)
        Kol_Company_serviced.append(company_serviced)






    print(f'Page {page_num} completed in {time.time()-start_time:.2f} seconds')

print("Total Time Completed in seconds", str(time.time()-total_time))

Page 1 completed in 5.44 seconds
Page 2 completed in 4.70 seconds
Page 3 completed in 4.51 seconds
Page 4 completed in 4.50 seconds
Page 5 completed in 3.80 seconds
Page 6 completed in 4.27 seconds
Page 7 completed in 4.06 seconds
Page 8 completed in 3.68 seconds
Page 9 completed in 3.82 seconds
Page 10 completed in 3.46 seconds
Page 11 completed in 4.84 seconds
Page 12 completed in 4.29 seconds
Page 13 completed in 3.84 seconds
Page 14 completed in 3.46 seconds
Page 15 completed in 3.65 seconds
Page 16 completed in 3.67 seconds
Total Time Completed in seconds 65.98866438865662

In [58]:
print(len(Kol_Hotel_Name))
print(len(Kol_Location))
print(len(Kol_ratings))
print(len(Kol_final_price))
print(len(Kol_Orginal_price))
print(len(Kol_Discount))
print(len(Kol_Taxes))
print(len(Kol_Wizard_member))
print(len(Kol_amenities))
print(len(Kol_Company_serviced))

248
248
248
248
248
248
248
248
248
248

In [59]:
for i,j in zip(Kol_Hotel_Name[:10],Kol_Location):
    print(i,j,sep='\n')

Collection O NSCB International Airport Formerly Raj Guest House
Kolkata International Airport  Gate no 2, Beside Phoenix Hospital & Diagnostics  11 Nirmal Sengupta Sarani Kolkata West Bengal
Hotel O Beleghata Formerly Santoshi Banquet And Marriage Hall
Dr. Suresh Chandra Banerjee Road, Kolkata
Super Townhouse VIP Road Formerly The Sky
Near Rani Tower, Tegharia, Kolkata
Super Collection O Jyotirindra Nandi Metro Station Kolkata Formerly Hotel Manurama
Santoshpur, Kolkata
Super Hotel O Kolkata Near Acropolis Mall Formerly 7 Horse GH
E.K.T, Kolkata
Super Collection O Salt Lake
Near 4 no. Tank Island, AE Block
Super Hotel O Ecopark Kolkata
Newtown, Kolkata
Super Townhouse Science City Formerly Hotel Mannat International
Topsia Crossing, Kolkata
Townhouse Belgharia Railway Station Kolkata Formerly BN Palace
Sukanta Pally Belghoria Expressway, Kolkata
Collection O Dalhousie Square Kolkata Formerly G.N Palace
24 RN Mukherjee Road,Bentick Street Cormer, Mission Row Extension

In [61]:
Hotel_Name=[]
Location=[]
ratings=[]
final_prices=[]
Orginal_prices=[]
Discounts=[]
Taxes=[]
Wizard_members=[]
amenities=[]
Company_serviceable=[]

In [64]:
Hotel_Name.extend(Hyd_Hotel_Name)
Location.extend(Hyd_Location)
ratings.extend(Hyd_ratings)
final_prices.extend(Hyd_final_price)
Orginal_prices.extend(Hyd_Orginal_price)
Discounts.extend(Hyd_Discount)
Taxes.extend(Hyd_Taxes)
Wizard_members.extend(Hyd_Wizard_member)
amenities.extend(Hyd_amenities)
Company_serviceable.extend(Hyd_Company_serviced)

In [69]:
Hotel_Name.extend(Bng_Hotel_Name)
Location.extend(Bng_Location)
ratings.extend(Bng_ratings)
final_prices.extend(Bng_final_price)
Orginal_prices.extend(Bng_Orginal_price)
Discounts.extend(Bng_Discount)
Taxes.extend(Bng_Taxes)
Wizard_members.extend(Bng_Wizard_member)
amenities.extend(Bng_amenities)
Company_serviceable.extend(Bng_Company_serviced)

In [71]:
Hotel_Name.extend(Del_Hotel_Name)
Location.extend(Del_Location)
ratings.extend(Del_ratings)
final_prices.extend(Del_final_price)
Orginal_prices.extend(Del_Orginal_price)
Discounts.extend(Del_Discount)
Taxes.extend(Del_Taxes)
Wizard_members.extend(Del_Wizard_member)
amenities.extend(Del_amenities)
Company_serviceable.extend(Del_Company_serviced)

In [73]:
Hotel_Name.extend(Mum_Hotel_Name)
Location.extend(Mum_Location)
ratings.extend(Mum_ratings)
final_prices.extend(Mum_final_price)
Orginal_prices.extend(Mum_Orginal_price)
Discounts.extend(Mum_Discount)
Taxes.extend(Mum_Taxes)
Wizard_members.extend(Mum_Wizard_member)
amenities.extend(Mum_amenities)
Company_serviceable.extend(Mum_Company_serviced)

In [75]:
Hotel_Name.extend(Che_Hotel_Name)
Location.extend(Che_Location)
ratings.extend(Che_ratings)
final_prices.extend(Che_final_price)
Orginal_prices.extend(Che_Orginal_price)
Discounts.extend(Che_Discount)
Taxes.extend(Che_Taxes)
Wizard_members.extend(Che_Wizard_member)
amenities.extend(Che_amenities)
Company_serviceable.extend(Che_Company_serviced)

In [77]:
Hotel_Name.extend(Pun_Hotel_Name)
Location.extend(Pun_Location)
ratings.extend(Pun_ratings)
final_prices.extend(Pun_final_price)
Orginal_prices.extend(Pun_Orginal_price)
Discounts.extend(Pun_Discount)
Taxes.extend(Pun_Taxes)
Wizard_members.extend(Pun_Wizard_member)
amenities.extend(Pun_amenities)
Company_serviceable.extend(Pun_Company_serviced)

In [79]:
Hotel_Name.extend(Kol_Hotel_Name)
Location.extend(Kol_Location)
ratings.extend(Kol_ratings)
final_prices.extend(Kol_final_price)
Orginal_prices.extend(Kol_Orginal_price)
Discounts.extend(Kol_Discount)
Taxes.extend(Kol_Taxes)
Wizard_members.extend(Kol_Wizard_member)
amenities.extend(Kol_amenities)
Company_serviceable.extend(Kol_Company_serviced)

In [84]:

oyo_rooms = pd.DataFrame({
    "Hotel_Name": Hotel_Name,
    "Location": Location,
    "Ratings": ratings,
    "Final_Price": final_prices,
    "Original_Price": Orginal_prices,
    "Discount": Discounts,
    "Taxes": Taxes,
    "Wizard_Member": Wizard_members,
    "Amenities": amenities,
    "Company_Serviced": Company_serviceable
})

In [85]:
oyo_rooms.shape

(1791, 10)

In [87]:
oyo_rooms.head()

,Hotel_Name,Location,Ratings,Final_Price,Original_Price,Discount,Taxes,Wizard_Member,Amenities,Company_Serviced
0,Townhouse Narayanaguda Metro Station Formerly ...,"Near Old MLA Quarters, Himayathnagar, Hyderabad",4.3 (774 Ratings)·Very Good,₹1730,₹7095,71% off,+ ₹257 taxes & fees · per room per night,WIZARD MEMBER,Parking facility Dining area Free Wifi + 14...,Yes
1,Townhouse Kothapet Formerly Surabhi Elite,"Kothapet, Hyderabad",4.5 (320 Ratings)·Excellent,₹1363,₹7695,79% off,+ ₹239 taxes & fees · per room per night,WIZARD MEMBER,Free Wifi Power backup Parking + 10 more,Yes
2,Townhouse Oak Madhapur Nera Regency,"Madhapur, Hyderabad",4.3 (1793 Ratings)·Very Good,₹1605,₹6498,72% off,+ ₹169 taxes & fees · per room per night,WIZARD MEMBER,Dining area Power backup Parking + 29 more,Yes
3,Hotel O by OYO Saraswathi Residency Near SR Na...,"Near Nalanda School, S.R. Nagar, Hyderabad",4.3 (6 Ratings)·Very Good,₹1332,₹5381,71% off,+ ₹175 taxes & fees · per room per night,NaN,Elevator Free Wifi Geyser + 8 more,No
4,Super Townhouse OAK Hotel Belsons Taj Mahal,"Near Swapnalok Complex, Patny Centre, Hyderabad",4.6 (82 Ratings)·Excellent,₹1963,₹7942,72% off,+ ₹261 taxes & fees · per room per night,NaN,Living Room Reception Toiletries available ...,No

In [89]:
oyo_rooms.tail()

,Hotel_Name,Location,Ratings,Final_Price,Original_Price,Discount,Taxes,Wizard_Member,Amenities,Company_Serviced
1786,Spot On Sonar Bangla Lodge,"Near Howrah railway station, Howrah AC Market,...",3.2 (62 Ratings)·Fair,₹917,₹3336,68% off,+ ₹131 taxes & fees · per room per night,NaN,Private entrance Parking facility Reception ...,No
1787,Hotel O Mominpur Guest House,"Braunfield Road Mominpore Kolkata, Kolkata",4.8 (82 Ratings)·Excellent,₹955,₹3733,70% off,+ ₹140 taxes & fees · per room per night,WIZARD MEMBER,Reception Free Wifi Geyser + 4 more,No
1788,Hotel O Sigma,"Near Buxarah Road, Howrah, Kolkata",3.6 (19 Ratings)·Good,₹907,₹3286,68% off,+ ₹141 taxes & fees · per room per night,NaN,Free Wifi Geyser Power backup + 6 more,No
1789,Hotel O by OYO Annapurna Plaza,"Market Street, Kolkata",3.0 (1 Ratings)·Fair,₹1330,₹6066,74% off,+ ₹195 taxes & fees · per room per night,NaN,AC TV,No
1790,Hotel O by OYO 4 Friends Hotel Unit : II,"New Town, Kolkata",3.8 (3 Ratings)·Good,₹974,₹3985,71% off,+ ₹142 taxes & fees · per room per night,NaN,Elevator Free Wifi Geyser + 3 more,No

In [90]:
oyo_rooms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1791 entries, 0 to 1790
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Hotel_Name        1791 non-null   object
 1   Location          1791 non-null   object
 2   Ratings           1791 non-null   object
 3   Final_Price       1791 non-null   object
 4   Original_Price    1791 non-null   object
 5   Discount          1791 non-null   object
 6   Taxes             1791 non-null   object
 7   Wizard_Member     968 non-null    object
 8   Amenities         1790 non-null   object
 9   Company_Serviced  1791 non-null   object
dtypes: object(10)
memory usage: 140.1+ KB

In [92]:
def wizard_classification(x):
    if x=='WIZARD MEMBER':
        return 'Yes'
    else:
        return 'No'
oyo_rooms['Wizard_Member']=oyo_rooms['Wizard_Member'].apply(wizard_classification)

In [93]:
oyo_rooms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1791 entries, 0 to 1790
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Hotel_Name        1791 non-null   object
 1   Location          1791 non-null   object
 2   Ratings           1791 non-null   object
 3   Final_Price       1791 non-null   object
 4   Original_Price    1791 non-null   object
 5   Discount          1791 non-null   object
 6   Taxes             1791 non-null   object
 7   Wizard_Member     1791 non-null   object
 8   Amenities         1790 non-null   object
 9   Company_Serviced  1791 non-null   object
dtypes: object(10)
memory usage: 140.1+ KB

In [94]:
oyo_rooms['Amenities'].fillna(oyo_rooms['Amenities'].mode()[0],inplace=True)

In [95]:
oyo_rooms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1791 entries, 0 to 1790
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Hotel_Name        1791 non-null   object
 1   Location          1791 non-null   object
 2   Ratings           1791 non-null   object
 3   Final_Price       1791 non-null   object
 4   Original_Price    1791 non-null   object
 5   Discount          1791 non-null   object
 6   Taxes             1791 non-null   object
 7   Wizard_Member     1791 non-null   object
 8   Amenities         1791 non-null   object
 9   Company_Serviced  1791 non-null   object
dtypes: object(10)
memory usage: 140.1+ KB

In [96]:
oyo_rooms.to_csv('Uncleaned_oyo_rooms.csv',mode='x')

In [97]:
oyo_rooms.head()

,Hotel_Name,Location,Ratings,Final_Price,Original_Price,Discount,Taxes,Wizard_Member,Amenities,Company_Serviced
0,Townhouse Narayanaguda Metro Station Formerly ...,"Near Old MLA Quarters, Himayathnagar, Hyderabad",4.3 (774 Ratings)·Very Good,₹1730,₹7095,71% off,+ ₹257 taxes & fees · per room per night,Yes,Parking facility Dining area Free Wifi + 14...,Yes
1,Townhouse Kothapet Formerly Surabhi Elite,"Kothapet, Hyderabad",4.5 (320 Ratings)·Excellent,₹1363,₹7695,79% off,+ ₹239 taxes & fees · per room per night,Yes,Free Wifi Power backup Parking + 10 more,Yes
2,Townhouse Oak Madhapur Nera Regency,"Madhapur, Hyderabad",4.3 (1793 Ratings)·Very Good,₹1605,₹6498,72% off,+ ₹169 taxes & fees · per room per night,Yes,Dining area Power backup Parking + 29 more,Yes
3,Hotel O by OYO Saraswathi Residency Near SR Na...,"Near Nalanda School, S.R. Nagar, Hyderabad",4.3 (6 Ratings)·Very Good,₹1332,₹5381,71% off,+ ₹175 taxes & fees · per room per night,No,Elevator Free Wifi Geyser + 8 more,No
4,Super Townhouse OAK Hotel Belsons Taj Mahal,"Near Swapnalok Complex, Patny Centre, Hyderabad",4.6 (82 Ratings)·Excellent,₹1963,₹7942,72% off,+ ₹261 taxes & fees · per room per night,No,Living Room Reception Toiletries available ...,No